name: Conventional Commits

on:
  pull_request:
    branches:
      - dev
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: webiny/action-conventional-commits@faccb24fc2550dd15c0390d944379d2d8ed9690e # v1.3.1
        with:
          allowed-commit-types: "feat,fix,chore,docs,style,refactor,perf,test,build,ci,revert,breaking"
